version: "3.9"

services:
  #===================
  # PostgreSQL
  #===================
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env.postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - opsync-net

  #===================
  # Redis
  #===================
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - opsync-net


  # ===========================
  # Auth Service
  # ===========================
  auth-service:
    container_name: auth-service
    restart: unless-stopped
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    env_file:
      - ./auth-service/.env.docker
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - redis
      - notification-service
    networks:
      - opsync-net

  # ===========================
  # Notification Service
  # ===========================
  notification-service:
    container_name: notification-service
    restart: unless-stopped
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    env_file:
      - ./notification-service/.env.docker
    ports:
      - "4002:4002"
    depends_on:
      - postgres
      - redis
    networks:
      - opsync-net

  # ===========================
  # API Gateway (Optional)
  # ===========================
  gateway:
    container_name: gateway
    restart: unless-stopped
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    env_file:
      - ./api-gateway/.env.docker
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
    networks:
      - opsync-net

# ===========================
# Volumes
# ===========================
volumes:
  postgres_data:

# ===========================
# Network
# ===========================
networks:
  opsync-net:
    driver: bridge
